jenkinsci/repo-plugin

- checkstyle.xml
- src/main/java/hudson/plugins/repo/ChangeLog.java
- src/main/java/hudson/plugins/repo/RepoScm.java
- src/main/resources/hudson/plugins/repo/RepoScm/config.jelly
- src/main/webapp/help-firstParent.html
- src/main/webapp/help-showAllChanges.html
This adds an option to select whether or not --first-parent is
passed to "git log" when determining the changelog.  The default
value is to include it.
> Add option for --first-parent in changelog

- pom.xml
- src/main/java/hudson/plugins/repo/RepoScm.java
- src/main/resources/hudson/plugins/repo/RepoScm/config.jelly
- src/main/webapp/help-forceSync.html
This adds a new checkbox option called "Force Sync" which will add the --force-sync option when running "repo sync".
> Add Force Sync option to repo plugin

- checkstyle.xml
- pom.xml
- src/main/java/hudson/plugins/repo/RepoScm.java
- src/main/java/hudson/plugins/repo/TagAction.java
- src/main/resources/hudson/plugins/repo/RepoScm/config.jelly
- src/main/webapp/help-noTags.html
This series updates the parent to 1.580.1 to enable @DataBoundSetter.
The version number is according to https://github.com/jenkinsci/workflow-plugin/blob/master/COMPATIBILITY.md#plugin-developer-guide.
Then, repo sync --no-tags support is added.
Fixes JENKINS-30618.
> Add support for repo sync --no-tags

- checkstyle.xml
- src/main/java/hudson/plugins/repo/RepoScm.java
Update the plugin according to the workflow compatibility guidelines: https://github.com/jenkinsci/workflow-plugin/blob/master/COMPATIBILITY.md, to support using as part of a workflow.
This fixes https://issues.jenkins-ci.org/browse/JENKINS-26836.
> [JENKINS-26836] Workflow support

- src/main/java/hudson/plugins/repo/RepoScm.java
- src/main/resources/hudson/plugins/repo/RepoScm/config.jelly
- src/main/webapp/help-ignoreChanges.html
- src/test/java/hudson/plugins/repo/TestRepoScm.java
This adds an ability to "ignore" changes on specific project while "polling" for changes from the scm.
This is useful for example when the build process itself commits a change to specific repository, to avoid re-trigger the build.
> adding an option to ignore specific projects on scm poll.

- src/main/java/hudson/plugins/repo/ChangeLogEntry.java
The Email Ext plugin tries to send email to the commits and the repo plugin
returns the committers full name instead of the email address.  This
causes the Email Ext to send emails for "John Doe <jdoe@jenkins.com>" to
"John@jenkins.com" and "Doe@jenkins.com" instead of jdoe@jenkins.com.
Fixes JENKINS-14539.
> Fix issue with Email Ext plugin - full name was returned instead of email

- src/main/java/hudson/plugins/repo/RepoScm.java
Variable expansion works for all other fields, but not for the local manifest. This makes it impossible to define the local manifest or its URL using environment variables or a pre SCM step.
My only concern about this change is that there might be a good reason why it was not implemented for the local manifest so far. If so I could improve the pull request and add a checkbox like "Do not expand variables in local manifest".
Also see https://issues.jenkins-ci.org/browse/JENKINS-37416 .
> Expand local manifest

- src/main/webapp/help-localManifest.html
Just fixed two typos in the help text.
> Fix typos in local manifest help

- src/main/java/hudson/plugins/repo/ChangeLog.java
- src/main/java/hudson/plugins/repo/ChangeLogEntry.java
- src/main/java/hudson/plugins/repo/ProjectState.java
- src/main/java/hudson/plugins/repo/RepoChangeLogSet.java
- src/main/java/hudson/plugins/repo/RepoScm.java
- src/main/java/hudson/plugins/repo/RevisionState.java
- src/main/java/hudson/plugins/repo/TagAction.java
The analysis in JENKINS-36703 was right, instead of `null` `SCMRevisionState.NONE` should have been returned and properly handled. This is done in b760e06. The other commit is unrelated, so in case upstream does not support these stylistic changes, it might just cherry-pick the first one.
> Fix polling behaviour

- src/main/java/hudson/plugins/repo/RepoScm.java
Commands 'repo forall -c "git reset --hard"' and "repo manifest"
didn't work because environnement was not injected  when command
was executed
Signed-off-by: Sébastien Mennetrier <smennetrier@voxtok.com>
> Fix some repo commands

- src/main/java/hudson/plugins/repo/RepoScm.java
- src/main/webapp/help-localManifest.html
Using .repo/local_manifest.xml has been deprecated for a while, and
prints a warning which dirtys the build log, so adopt the new convention
of .repo/local_manifests/*.xml. I arbitrarily chose "local.xml" for the
file name.
Change-Id: Iaef7077312ce8a1cb195143011ca4ebcaf9e209b
> Use local_manifests/local.xml rather than local_manifest.xml

- src/main/webapp/help-forceSync.html
From the repo sync help page as of the latest release v1.12.37, the
--force-sync option is used to overwrite an existing project git
directory if it needs to point to a different object directory.
Currently, the help uses the description for -f, --force-broken instead
of --force-sync.
> Fix --force-sync help description

- src/main/java/hudson/plugins/repo/RepoScm.java
Added support for evaluating ${param} in destination dir just like
it is done for the other configuration parameters.
> Support for evaluating ${param} in destination dir

- src/main/resources/hudson/plugins/repo/RepoScm/config.jelly
When loading the job config into the job configuration GUI, the
repo-plugin properties are empty. The config file contains the values,
but the plugin is unable to populate config values from the file.
If the user edits anything at job configuration page and saves, the
empty repo-plugin properties are written to file and are cleared!
This patch fixes the problem by populating the values from the config
file to the GUI.
> Fix problem with populating values from config when using pipeline

- src/main/java/hudson/plugins/repo/ChangeLog.java
- src/main/java/hudson/plugins/repo/ChangeLogEntry.java
The old code assumed the action/path were always at fixed positions in the line. This is not the case for at least 2 reasons:
- The length of abbreviated SHAs varies.
- The action can be followed by a score (for renames/copies).
The new code splits by space/tab as per the format described in "git diff --help". This could still break if you have filenames containing tabs but it's certainly better.
I've also gotten rid of the made-up rename EditType and just used an add+delete instead. Without support for renaming at a higher level this seems better.
> Fix raw diff parsing

- src/main/java/hudson/plugins/repo/RepoScm.java
- src/main/resources/hudson/plugins/repo/RepoScm/config.jelly
- src/main/webapp/help-noCloneBundle.html
Added "No Clone Bundle" setting. If selected the "repo init" and "repo sync" commands will
be run with the --no-clone-bundle option.
I have tried it with both standard jobs and pipelines.
> Added support for --no-clone-bundle

- src/main/java/hudson/plugins/repo/ChangeLog.java
- src/main/java/hudson/plugins/repo/RepoScm.java
- src/main/resources/hudson/plugins/repo/RepoChangeLogSet/digest.jelly
- src/main/resources/hudson/plugins/repo/RepoChangeLogSet/index.jelly
A very strong limit to using from pipeline is that "contextual" environment variable (set during the job) cannot be accessed from the SCM [1]. To overcome this, this allow explicitely passing the environment variables from the checkout step.
It is now possible to use ssh agent or withEnv() block with repo checkout in Jenkins pipelines, like in the following code:
```groovy
sshAgent(['gerrit-ssh-credentials-id']) {
checkout([$class: 'RepoScm', manifestRepositoryUrl: 'ssh://server/project',
extraEnvVars: getContext(hudson.EnvVars)])
}
```
The pull request also includes a few minor changes:
* Fix crash when used from pipeline and changelog is empty.
* Include revision for new projects in changes view.
* In detailed view, hide missing fields: e.g. revision, author and commiter for new or …
> [JENKINS-37557] Better support for pipelines

- doc/README.adoc
- pom.xml
- src/test/java/hudson/plugins/repo/RepoScmTest.java
Following the instructions and motivations here https://jenkins.io/blog/2019/10/21/plugin-docs-on-github/
Also updated core to slightly more modern incarnation to avoid strangeness with new plugin pom version.
> Moved documentation from wiki to GitHub repo + modern Jenkins core 

- src/main/java/hudson/plugins/repo/RepoScm.java
- src/main/resources/hudson/plugins/repo/RepoScm/config.jelly
- src/main/webapp/help-currentBranch.html
- src/main/webapp/help-fetchSubmodules.html
- src/main/webapp/help-manifestPlatform.html
- src/main/webapp/help-manifestSubmodules.html
- src/main/webapp/help-noTags.html
Support some missing repo flags/options:
* Allow specifying platform in `repo init`
* Allow handling submodules (`repo init --submodules` and `repo fetch --fetch-submodules`)
* Apply `noTags` and `currentBranch` to repo init as well
> Add missing repo options; specifying platform, init --submodules and fetch --fetch-submodules, noTags and currentBranch

- src/main/java/hudson/plugins/repo/RepoScm.java
Change-Id: I46f02494f90719ca89db2a1722cd5ed9a1951f18
> Fix invalid platform flag issue

- src/main/java/hudson/plugins/repo/RepoScm.java
- src/main/resources/hudson/plugins/repo/RepoScm/config.jelly
- src/main/webapp/help-repoBranch.html
With python3 arriving at repo, google introduced the repo-1 or maint branch to not break old installations. This commit facilitates this.
> Add support for repo-branch

- pom.xml
- src/main/java/hudson/plugins/repo/ManifestAction.java
- src/main/java/hudson/plugins/repo/RepoScm.java
- src/main/java/hudson/plugins/repo/RevisionState.java
- src/main/resources/hudson/plugins/repo/ManifestAction/index.jelly
- src/test/java/hudson/plugins/repo/TestRevisionState.java
Better handle performing multiple checkouts from the same build:
* Match manifest url/branch/file to compute changes
* Store extra index in ManifestAction to display each manifest
* Display the manifest url/branch/file in manifest action
> Multiple checkout

- checkstyle.xml
- src/main/java/hudson/plugins/repo/ChangeLog.java
When performing shallow checkout, the 'previous' revision may not be
present, which causes the `git log` command to fail.
When this happens, simply show HEAD in change in changelog, like the git
plugin does.
> Support changelog with shallow checkout

- Jenkinsfile
Checkstyle and spotbugs are being enabled by default in https://github.com/jenkins-infra/pipeline-library/pull/121, (assuming that checkstyle is bound to a phase in the build directly, the task is no longer directly invoked)
> Remove unneeded configuration from buildPlugin

- src/main/java/hudson/plugins/repo/RepoScm.java
- src/main/resources/hudson/plugins/repo/RepoScm/config.jelly
- src/main/webapp/help-worktree.html
- src/test/java/hudson/plugins/repo/TestRepoScm.java
The "worktree" option is absolutely necessary under Windows to not use symlink which requires administration rights.
> Add option to enable --worktree option to repo init

- pom.xml
- src/main/java/hudson/plugins/repo/RepoScm.java
Cleanup local manifest from a previous build before initializing workspace. This fix "checkout" when previous build has a bad local manifest (repo init command failed)
> Fix "checkout" when previous build has a bad local manifest

- pom.xml
Update made on PR https://github.com/jenkinsci/repo-plugin/pull/74 broke https://plugins.jenkins.io/repo/ because line below was not updated https://github.com/jenkinsci/repo-plugin/blob/729f5c57bf4cd8fe31f6502c90854ba0f24de464/pom.xml#L16.
Thanks to @daniel-beck for reporting this isssue
> Fix broken jenkins plugin documentation

- src/main/java/hudson/plugins/repo/RepoScm.java
- src/main/resources/hudson/plugins/repo/RepoScm/buildEnv.properties
The value of an environment variable can't be greater than MAX_ARG_STRLEN, which is PAGE_SIZE * 32, aka 131072 bytes.
> Add static manifest into environment variables when we can.
